name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_dir:
          - 3.0/async/pekko-examples
          - 3.0/formats/scalatra-forms
          - 3.0/http/authentication-demo
          - 3.0/http/scalatra-gzip
          - 3.0/http/scalatra-http-demo
          - 3.0/http/scentry-auth-demo
          - 3.0/persistence/scalatra-slick
          - 3.0/persistence/scalatra-squeryl
          - 3.0/views/scalatra-twirl
          - 3.0/swagger-example
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: "temurin"
    - name: Run tests
      env:
        TEST_DIR: ${{ matrix.test_dir }} 
      run: cd $TEST_DIR && sbt test
